name: trace-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pydm
  - pandas
  - pytest
  - pytest-qt
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - pre-commit
  - flake8
  - pip
  - pip:
    - ufmt
